 // Sample bus stop data (replace with your actual data source)
 export const existingBusStops = [
    {
      id: "BS001",
      stopName: "Fort Railway Station",
      stopCode: "BS001",
      latitude: "6.9271",
      longitude: "79.8612",
      address: "Fort Railway Station, Colombo Fort",
      city: "Colombo",
      district: "Colombo",
      province: "Western",
      stopType: "Terminal",
      status: "Active",
      nearbyLandmarks: "Near Central Bank, Fort Railway Station",
      notes: "Main bus terminal in Colombo Fort area",
      facilities: {
        shelter: true,
        seating: true,
        lighting: true,
        cctv: true,
        ticketCounter: true,
        restrooms: true,
        parking: false,
        wheelchairAccess: true,
        digitalDisplay: true,
        wifi: false,
      }
    },
    {
      id: "BS002",
      stopName: "Pettah Central Bus Stand",
      stopCode: "BS002",
      latitude: "6.9344",
      longitude: "79.8428",
      address: "Main Street, Pettah, Colombo",
      city: "Colombo",
      district: "Colombo",
      province: "Western",
      stopType: "Terminal",
      status: "Active",
      nearbyLandmarks: "Near Pettah Market, Khan Clock Tower",
      notes: "Central bus terminal serving multiple routes",
      facilities: {
        shelter: true,
        seating: true,
        lighting: true,
        cctv: true,
        ticketCounter: true,
        restrooms: true,
        parking: true,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS003",
      stopName: "Kandy Clock Tower",
      stopCode: "BS003",
      latitude: "7.2906",
      longitude: "80.6337",
      address: "Dalada Veediya, Kandy",
      city: "Kandy",
      district: "Kandy",
      province: "Central",
      stopType: "Regular",
      status: "Active",
      nearbyLandmarks: "Temple of the Tooth, Kandy Lake",
      notes: "Historic bus stop near the famous clock tower",
      facilities: {
        shelter: true,
        seating: false,
        lighting: true,
        cctv: false,
        ticketCounter: false,
        restrooms: false,
        parking: false,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS004",
      stopName: "Galle Bus Terminal",
      stopCode: "BS004",
      latitude: "6.0535",
      longitude: "80.221",
      address: "Galle Bus Stand, Galle",
      city: "Galle",
      district: "Galle",
      province: "Southern",
      stopType: "Terminal",
      status: "Active",
      nearbyLandmarks: "Galle Fort, Dutch Hospital",
      notes: "Main terminal for southern province routes",
      facilities: {
        shelter: true,
        seating: true,
        lighting: true,
        cctv: true,
        ticketCounter: true,
        restrooms: true,
        parking: true,
        wheelchairAccess: true,
        digitalDisplay: true,
        wifi: true,
      }
    },
    {
      id: "BS005",
      stopName: "Negombo Bus Stand",
      stopCode: "BS005",
      latitude: "7.2083",
      longitude: "79.8358",
      address: "Main Road, Negombo",
      city: "Negombo",
      district: "Gampaha",
      province: "Western",
      stopType: "Regular",
      status: "Active",
      nearbyLandmarks: "Negombo Beach, Fish Market",
      notes: "Busy bus stop serving airport and beach routes",
      facilities: {
        shelter: true,
        seating: true,
        lighting: true,
        cctv: false,
        ticketCounter: false,
        restrooms: false,
        parking: false,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS006",
      stopName: "Anuradhapura New Bus Stand",
      stopCode: "BS006",
      latitude: "8.3114",
      longitude: "80.4037",
      address: "New Town, Anuradhapura",
      city: "Anuradhapura",
      district: "Anuradhapura",
      province: "North Central",
      stopType: "Terminal",
      status: "Maintenance",
      nearbyLandmarks: "Sacred City, Ruwanwelisaya",
      notes: "Under maintenance - renovating facilities",
      facilities: {
        shelter: true,
        seating: false,
        lighting: false,
        cctv: false,
        ticketCounter: false,
        restrooms: false,
        parking: true,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS007",
      stopName: "Matara Bus Terminal",
      stopCode: "BS007",
      latitude: "5.9549",
      longitude: "80.555",
      address: "Matara Main Road, Matara",
      city: "Matara",
      district: "Matara",
      province: "Southern",
      stopType: "Terminal",
      status: "Active",
      nearbyLandmarks: "Matara Beach, Star Fort",
      notes: "Terminal serving deep south routes",
      facilities: {
        shelter: true,
        seating: true,
        lighting: true,
        cctv: true,
        ticketCounter: true,
        restrooms: true,
        parking: false,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS008",
      stopName: "Kurunegala Bus Stand",
      stopCode: "BS008",
      latitude: "7.4818",
      longitude: "80.3609",
      address: "Clock Tower Road, Kurunegala",
      city: "Kurunegala",
      district: "Kurunegala",
      province: "North Western",
      stopType: "Regular",
      status: "Active",
      nearbyLandmarks: "Kurunegala Lake, Elephant Rock",
      notes: "Central hub for North Western province",
      facilities: {
        shelter: true,
        seating: true,
        lighting: true,
        cctv: false,
        ticketCounter: false,
        restrooms: true,
        parking: false,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS009",
      stopName: "Ratnapura Bus Terminal",
      stopCode: "BS009",
      latitude: "6.6828",
      longitude: "80.4126",
      address: "Main Street, Ratnapura",
      city: "Ratnapura",
      district: "Ratnapura",
      province: "Sabaragamuwa",
      stopType: "Terminal",
      status: "Active",
      nearbyLandmarks: "Gem Market, Maha Saman Devalaya",
      notes: "Gateway to hill country and gem mining areas",
      facilities: {
        shelter: true,
        seating: false,
        lighting: true,
        cctv: false,
        ticketCounter: true,
        restrooms: false,
        parking: true,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
    {
      id: "BS010",
      stopName: "Badulla Bus Stand",
      stopCode: "BS010",
      latitude: "6.9934",
      longitude: "81.055",
      address: "Lower Street, Badulla",
      city: "Badulla",
      district: "Badulla",
      province: "Uva",
      stopType: "Regular",
      status: "Maintenance",
      nearbyLandmarks: "Badulla Railway Station, Dunhinda Falls",
      notes: "Hill country terminal - under renovation",
      facilities: {
        shelter: false,
        seating: false,
        lighting: false,
        cctv: false,
        ticketCounter: false,
        restrooms: false,
        parking: false,
        wheelchairAccess: false,
        digitalDisplay: false,
        wifi: false,
      }
    },
  ]