// import { BusStopResponse } from "@/types/responsedto/bus-stop";

// export const sriLankanBusStops: BusStopResponse[] = [
//   {
//     id: "BS001",
//     name: "Fort Railway Station",
//     latitude: 6.9271,
//     longitude: 79.8612,
//     city: "Colombo",
//     province: "Western",
//     status: "Active",
//   },
//   {
//     id: "BS002",
//     name: "Pettah Central Bus Stand",
//     latitude: 6.9344,
//     longitude: 79.8428,
//     city: "Colombo",
//     province: "Western",
//     status: "Active",
//   },
//   {
//     id: "BS003",
//     name: "Kandy Clock Tower",
//     latitude: 7.2906,
//     longitude: 80.6337,
//     city: "Kandy",
//     province: "Central",
//     status: "Active",
//   },
//   {
//     id: "BS004",
//     name: "Galle Bus Terminal",
//     latitude: 6.0535,
//     longitude: 80.221,
//     city: "Galle",
//     province: "Southern",
//     status: "Active",
//   },
//   {
//     id: "BS005",
//     name: "Negombo Bus Stand",
//     latitude: 7.2083,
//     longitude: 79.8358,
//     city: "Negombo",
//     province: "Western",
//     status: "Active",
//   },
//   {
//     id: "BS006",
//     name: "Anuradhapura New Bus Stand",
//     latitude: 8.3114,
//     longitude: 80.4037,
//     city: "Anuradhapura",
//     province: "North Central",
//     status: "Maintenance",
//   },
//   {
//     id: "BS007",
//     name: "Matara Bus Terminal",
//     latitude: 5.9549,
//     longitude: 80.555,
//     city: "Matara",
//     province: "Southern",
//     status: "Active",
//   },
//   {
//     id: "BS008",
//     name: "Kurunegala Bus Stand",
//     latitude: 7.4818,
//     longitude: 80.3609,
//     city: "Kurunegala",
//     province: "North Western",
//     status: "Active",
//   },
//   {
//     id: "BS009",
//     name: "Ratnapura Bus Terminal",
//     latitude: 6.6828,
//     longitude: 80.4126,
//     city: "Ratnapura",
//     province: "Sabaragamuwa",
//     status: "Active",
//   },
//   {
//     id: "BS010",
//     name: "Badulla Bus Stand",
//     latitude: 6.9934,
//     longitude: 81.055,
//     city: "Badulla",
//     province: "Uva",
//     status: "Maintenance",
//   },
// ]


