import { BusPermit } from "@/components/mot/bus-permits-table";

export const permits: BusPermit[] = [
    {
      id: '001',
      routeNo: '001',
      routeName: 'Colombo - Kandy',
      operator: 'SLTB',
      validFrom: 'Jan 1, 2024',
      validUntil: 'Dec 31, 2024',
      status: 'Active',
    },
    {
      id: '002',
      routeNo: '002',
      routeName: 'Galle - Matara',
      operator: 'SLTB',
      validFrom: 'Mar 15, 2024',
      validUntil: 'Mar 14, 2025',
      status: 'Active',
    },
    {
      id: '003',
      routeNo: '003',
      routeName: 'Colombo - Kataragama',
      operator: 'Private',
      validFrom: 'Feb 1, 2024',
      validUntil: 'Jan 31, 2025',
      status: 'Pending',
    },
    {
      id: '004',
      routeNo: '004',
      routeName: 'Colombo - Mannar',
      operator: 'SLTB',
      validFrom: 'Jun 1, 2024',
      validUntil: 'May 31, 2025',
      status: 'Active',
    },
    {
      id: '005',
      routeNo: '005',
      routeName: 'Colombo - Kurunegala',
      operator: 'Private',
      validFrom: 'Apr 10, 2024',
      validUntil: 'Apr 9, 2025',
      status: 'Expired',
    },
    {
      id: '006',
      routeNo: '006',
      routeName: 'Jaffna - Vavuniya',
      operator: 'SLTB',
      validFrom: 'Jul 1, 2024',
      validUntil: 'Jun 30, 2025',
      status: 'Active',
    },
    {
      id: '007',
      routeNo: '007',
      routeName: 'Negombo - Anuradhapura',
      operator: 'Private',
      validFrom: 'May 20, 2024',
      validUntil: 'May 19, 2025',
      status: 'Pending',
    },
    {
      id: '008',
      routeNo: '008',
      routeName: 'Colombo - Trincomalee',
      operator: 'SLTB',
      validFrom: 'Aug 1, 2024',
      validUntil: 'Jul 31, 2025',
      status: 'Active',
    },
    {
      id: '009',
      routeNo: '009',
      routeName: 'Matara - Nuwara Eliya',
      operator: 'Private',
      validFrom: 'Feb 15, 2023',
      validUntil: 'Feb 14, 2024',
      status: 'Expired',
    },
    {
      id: '010',
      routeNo: '010',
      routeName: 'Batticaloa - Polonnaruwa',
      operator: 'SLTB',
      validFrom: 'Sep 1, 2024',
      validUntil: 'Aug 31, 2025',
      status: 'Active',
    },
    {
      id: '011',
      routeNo: '011',
      routeName: 'Colombo - Badulla',
      operator: 'SLTB',
      validFrom: 'Jan 15, 2024',
      validUntil: 'Jan 14, 2025',
      status: 'Active',
    },
    {
      id: '012',
      routeNo: '012',
      routeName: 'Kandy - Nuwara Eliya',
      operator: 'Private',
      validFrom: 'Mar 1, 2024',
      validUntil: 'Feb 28, 2025',
      status: 'Active',
    },
    {
      id: '013',
      routeNo: '013',
      routeName: 'Colombo - Hambantota',
      operator: 'SLTB',
      validFrom: 'Apr 1, 2024',
      validUntil: 'Mar 31, 2025',
      status: 'Pending',
    },
    {
      id: '014',
      routeNo: '014',
      routeName: 'Galle - Tissamaharama',
      operator: 'Private',
      validFrom: 'May 1, 2024',
      validUntil: 'Apr 30, 2025',
      status: 'Active',
    },
    {
      id: '015',
      routeNo: '015',
      routeName: 'Colombo - Chilaw',
      operator: 'SLTB',
      validFrom: 'Jun 15, 2024',
      validUntil: 'Jun 14, 2025',
      status: 'Active',
    },
    {
      id: '016',
      routeNo: '016',
      routeName: 'Ratnapura - Embilipitiya',
      operator: 'Private',
      validFrom: 'Jul 10, 2024',
      validUntil: 'Jul 9, 2025',
      status: 'Expired',
    },
    {
      id: '017',
      routeNo: '017',
      routeName: 'Ampara - Batticaloa',
      operator: 'SLTB',
      validFrom: 'Aug 15, 2024',
      validUntil: 'Aug 14, 2025',
      status: 'Active',
    },
    {
      id: '018',
      routeNo: '018',
      routeName: 'Monaragala - Wellawaya',
      operator: 'Private',
      validFrom: 'Sep 10, 2024',
      validUntil: 'Sep 9, 2025',
      status: 'Pending',
    },
  ];